volumes:
  cnp-data:
    external: true
services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /case-n-part
    volumes:
      - ./ghi/case-n-part:/case-n-part
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_ACCOUNTS_HOST: http://localhost:8000
  postgres:
    image: postgres:14-bullseye
    volumes:
      - ./data/postgres/init:/docker-entrypoint-initdb.d
      - cnp-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: great-value
      POSTGRES_USER: great-value
      POSTGRES_DB: great-value
    ports:
      - "15432:5432"
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: postgresql://great-value:great-value@postgres/great-value
      SECRET_KEY: fe9f6e232112f6a1075578cdd151b3a7ff3aa32c25d1dab913dfa16a989358c3
